### ISSUE TITLE
Ducted Gas Fan status always off

### ISSUE THREAD

**Issue by robertfgoodworth** [mantorok1/homebridge-rinnai-touch-platform#1]
Hi Mantorok1,

First let me say THANKYOU for developing this homebridge Rinnai touch plugin,  i'll look into to helping you financially. 
Now my reason for lodging an issue, not sure if it's a code issue or a problem between the chair and keyboard.
In homebridge and Home Assistant i'm not seeing any status changes for the heaters fan, seems to always be off, nor can I see fan rotation speeds. Is there something I'm doing wrong or can check to get this working?

Cheers

Robert Goodworth

**Comment by mantorok1** [comment]
Hi Robert,

Thanks for the kind offer to help out financially. I must publish some details for those that wish to donate. Stay tuned.

As for the fan issue you've raised are you talking about the "Circulation Fan" accessory/device in the iOS Home app?  This is used to control the fan when the heating/cooling is off as you may want to just circulate the air in your home. If you tap on this tile in the Home app on your iPhone it should turn off the heating/cooling and switch the fan on. When the fan is on you'll be able to control the rotation speeds.

The "Circulation fan" does not indicate that the fan is on or off while the Brivis HVAC is in heating or cooling modes. This is kind of indicated by the colour of the dot in the tile which displays the current temperature. Green = idle (fan is off), Orange = heating (fan is on), Blue = cooling (fan is on).

Regards,
Mantorok

**Comment by robertfgoodworth** [comment]
Hi Mantorok,

 

Ah I see said the blind man 😊. 

 

Why I was asking is because I purchased a humidifier with a RF Remote which I plan to use a RF rec/trans to turn on and off when the Brivis HVAC heating kicks in.  This big gas heater dries out the air to the point we wake up with dry mouths, my humidity meter show is down to 30% humidity, hoping this big 7L humidifier I’ll put in the heater air intake will help.  All I need is to workout how to create a binary sensor (was hoping MQTT from your Rinnai module) then create a Nodered workflow to turn the humidifier On when the heater on any zone starts.

 

Regards

 

Rob

**Comment by mantorok1** [comment]
No worries Rob,

I think you can do what you want using my plugin. Take a look at the `hvac/action/get` topic which will publish when the HVAC is actively heating. If it doesn't quite meet your needs let me know, I can always add another MQTT topic.

**Comment by robertfgoodworth** [comment]
THANKYOU
