### ISSUE TITLE
A way to use target temperature in an automation

### ISSUE THREAD

**Issue by VocalOverdub** [mantorok1/homebridge-rinnai-touch-platform#10]
**Is your feature request related to a problem? Please describe:**

I am trying to use the set temperature on the thermostat as a test condition for automations.

The Home app doesn't allow me to use the thermostat in an automation condition at all.  Eve lets me test against the mode (cool/heat/off) and temperature but, after a lot of bashing my head against the wall trying to work out why my automations weren't working, I discovered that the temperature value Eve lets me have is the detected temperature (which on my system is always 0, due to the Touch Wifi's limitations).

What I'm ultimately trying to achieve with my automations is to change the zone settings based on temperature sensors I've placed around the house.  Our HVAC system is not particularly well designed.  If we want to cool or heat both upstairs and downstairs, upstairs always reaches the target temperature much quicker than downstairs, but the system keeps on blowing everywhere until everything is at the target temperature.  At the moment, the result is that upstairs is like a refrigerator while downstairs is still warmer that we'd like it.  Switching the upstairs zone off in that situation helps with both of those issues (stops cooling upstairs, more cool air blowing downstairs).

So, in essence, I'm trying to set up an automation that triggers at regular intervals, checks the target temp on the thermostat against a sensor in each zone, and then turns the zone off if it's already at temperature.

**Describe the solution you'd like:**

For the lack of a better idea, would it be possible to add (optional) dummy switches which are switched on when their respective temperature is set on the thermostat, and off otherwise?

So, say, a switch for each of 16, 17, 18, 19 ... 24 (that's about as extensive a range as we use across the year).

I could then use those in my automation conditions.

**Describe alternatives you've considered:**

I imagine it would be non-trivial to get Apple or Eve to change the way their apps read thermostat data for automation conditions.

**Additional context:**

I hope that I'm not missing an obvious solution / just not operating the apps correctly.

Many thanks.

**Comment by mantorok1** [comment]
Hi @VocalOverdub, yeah the HomeKit automation can be a bit limited. One option you could try is MQTT. The plugin will report the target temperature via MQTT. You might then be able to use [node-red](https://nodered.org) or [homebridge-mqttthing](https://www.npmjs.com/package/homebridge-mqttthing) to do the automation you want.

**Comment by VocalOverdub** [comment]
Once again, thank you very much for being both helpful and quick.

I had seen MQTT mentioned in your documentation, but had no idea what it was.

I'm now running mosquitto and homebridge-mqttting, and have everything I need to do what I want.
