### ISSUE TITLE
Connection refused since upgrade to latest version?

### ISSUE THREAD

**Issue by erwinloh** [mantorok1/homebridge-rinnai-touch-platform#4]
**Describe Your Problem:**
The plugin is no longer connecting since I upgraded from previous version to current version.

**Logs:**
[Rinnai Touch] TCP Connection failed. Attempt 3 of 3 [Error: connect ECONNREFUSED 192.168.1.32:27847]

**Plugin Config:**

        {
            "platform": "RinnaiTouchPlatform",
            "plugin_map": {
                "plugin_name": "homebridge-rinnai-touch-platform"
            },
            "name": "Rinnai Touch",
            "controllerType": "T",
            "zoneType": "S",
            "showFan": true,
            "showAuto": false,
            "showAdvanceSwitches": false,
            "showManualSwitches": false,
            "seperateModeAccessories": false,
            "seperateFanZoneSwitches": false,
            "invertComfortLevel": true,
            "setAutoOperatingState": false,
            "showHomebridgeEvents": false,
            "showModuleEvents": false,
            "showModuleStatus": false,
            "clearCache": false,
            "forceAutoDiscovery": false,
            "mqtt": {
                "showMqttEvents": false,
                "subscribeTemperature": {}
            },
            "pushover": {
                "users": []
            }
        }

**Screenshots:**

**Environment:**

* **Plugin Version**: 3.3.4
Bridge Name | HOOBS
HOOBS Version | 3.3.5
Node Version | 14.15.1

**Comment by mantorok1** [comment]
Hi @erwinloh,

The connection to the module can be very temperamental. Sometimes it will recover by itself. Have you tried the suggestions at the bottom the README (https://www.npmjs.com/package/homebridge-rinnai-touch-platform)?
When this happens to me I find restarting my router will fix it up. But it can take several minutes in some cases

**Comment by erwinloh** [comment]
Hi mate - thanks for the response - all it took was switching off the network connection within the router to the Rinnai Touch device for 5 minutes, and turning it on again, without needing to reboot the router, and it worked!

**Comment by mantorok1** [comment]
That's awesome. Glad to hear its fixed now.
