### ISSUE TITLE
Crash when 2 rinnai touch units detected

### ISSUE THREAD

**Issue by jakubd2** [mantorok1/homebridge-rinnai-touch-platform#5]
**Describe The Bug:**

**To Reproduce:**

**Expected behavior:**

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by jakubd2** [comment]
Rinnae app recently updated allows 2 modules to connect everything crashed after that 
I can’t send any details because I can’t even open homebridge now

**Comment by mantorok1** [comment]
Hi @jakubd2,

So you have 2 Rinnai Touch WiFi modules in your home, is that right? Could you give me some more details about your HVAC system. Do you have 2 seperate gas heaters? Just wondering why you need 2 modules?

Are you able to supply your Homebridge config file?

I suspect that the plugin is having trouble identifying which module to connect to during auto discovery. One thing you could try is supplying the IP address of one of the modules in the plugin config. That will prevent the plugin from trying to auto discover the module.

It might be possible to connect to the 2nd module by using a Child Bridge in Homebridge. Or failing that another instance of Homebridge with the plugin installed. Again you’ll have to supply the IP address of the 2nd module in the config.

For the above to work you need to give the 2 modules static IP addresses.

**Comment by jakubd2** [comment]
Hey matorok 1
 2 story house 
Gas heater/ refrigeration aircon setup for each floor 
I can’t send you the config because I had to unistall home bridge
These Rinnai units are the only thing I use home bridge for
Thanks very much for the suggestions 
I will let you know how I go
Regards 
jakubd2

**Comment by mantorok1** [comment]
Thanks @jakubd2 , yes please let me know how it goes. It's a valid use case so I'll update the README in case others have this issue in the future.

**Comment by jakubd2** [comment]
Hey mantorok1
Using child bridge, Platform still doesn’t seem to allow entry of second module

**Comment by mantorok1** [comment]
Did you manage to get one to work?

Can you post the config which you're using?

Not sure if this is useful but I found this issue which talks about using child bridges to have 2 instances of the same plugin: https://github.com/homebridge/homebridge/issues/2845

**Comment by mantorok1** [comment]
Hi @jakubd2,

I had a go at adding 2 child bridges on my own setup and managed to get it working. As I only have the one module I can't test the connectivity but I can't see a reason why it shouldn't work. Here's the config I used:
```
        {
            "name": "Upstairs",
            "address": "192.168.1.60",
            "showModuleEvents": true,
            "_bridge": {
                "username": "A1:B2:C3:D4:E5:F0",
                "port": 42150
            },
            "platform": "RinnaiTouchPlatform"
        },
        {
            "name": "Downstairs",
            "address": "192.168.1.61",
            "showModuleEvents": true,
            "_bridge": {
                "username": "A1:B2:C3:D4:E5:F1",
                "port": 42151
            },
            "platform": "RinnaiTouchPlatform"
        }
```
The values for `address`, `username` and `port` must be unique for this to work.
Here's the Homebridge log showing how both instances of the plugin are attempting to connect to the modules but fail because there is no module at the above IP addresses:
```
[4/24/2021, 11:50:23 AM] [Downstairs] TCP Connection failed. Attempt 1 of 3 [Error: connect ECONNREFUSED 192.168.1.61:27847]
[4/24/2021, 11:50:28 AM] [Upstairs] TCP Connection failed. Attempt 1 of 3 [Error: TCP Connection timed out]
```

One thing I noticed is that the Homebridge Config UI doesn't allow you edit both configs via its `SETTINGS` option but you can edit both via the `JSON Config` editor

**Comment by jakubd2** [comment]
Thank you very much Jakub

**Comment by jakubd2** [comment]
Hey mantorok
I’m not good with json 
I can’t seem to get the plug in to allow second bridge creation
Cheers 
Jakub

**Comment by mantorok1** [comment]
Can you paste your current config here so I can take a look

**Comment by jakubd2** [comment]
To view my file, click this link:
https://1drv.ms/w/s!AnZWIawvQH1CgYV0BQlB-JJcwSeqYA


Sent from Jakub's phone

**Comment by mantorok1** [comment]
Hi @jakubd2,

The file only contains the config for 1 module. You need to specify the 2nd one. Something like this:
```
{ 
    "bridge": { 
        "name": "Homebridge 2A5E", 
        "username": "0E:C9:0D:2A:2A:5E", 
        "port": 51456, 
        "pin": "672-56-796" 
    }, 
    "accessories": [], 
    "platforms": [ 
        { 
            "name": "Config", 
            "port": 8581, 
            "platform": "config" 
        }, 
        { 
            "name": "Rinnai touch 1", 
            "address": "10.1.1.67", 
            "controllerType": "T", 
            "zoneType": "S", 
            "showFan": false, 
            "showAuto": false, 
            "showAdvanceSwitches": false, 
            "showManualSwitches": false, 
            "seperateModeAccessories": false, 
            "seperateFanZoneSwitches": false, 
            "invertComfortLevel": true, 
            "setAutoOperatingState": true, 
            "showHomebridgeEvents": true, 
            "showModuleEvents": true, 
            "showModuleStatus": false, 
            "clearCache": false, 
            "forceAutoDiscovery": false, 
            "mqtt": { 
                "showMqttEvents": true 
            }, 
            "_bridge": { 
                "username": "0E:2B:82:59:7C:9F", 
                "port": 55645 
            }, 
            "platform": "RinnaiTouchPlatform" 
        } ,
        { 
            "name": "Rinnai touch 2", 
            "address": "10.1.1.68", 
            "controllerType": "T", 
            "zoneType": "S", 
            "showFan": false, 
            "showAuto": false, 
            "showAdvanceSwitches": false, 
            "showManualSwitches": false, 
            "seperateModeAccessories": false, 
            "seperateFanZoneSwitches": false, 
            "invertComfortLevel": true, 
            "setAutoOperatingState": true, 
            "showHomebridgeEvents": true, 
            "showModuleEvents": true, 
            "showModuleStatus": false, 
            "clearCache": false, 
            "forceAutoDiscovery": false, 
            "mqtt": { 
                "showMqttEvents": true 
            }, 
            "_bridge": { 
                "username": "0E:2B:82:59:7C:A0", 
                "port": 55646 
            }, 
            "platform": "RinnaiTouchPlatform" 
        }
    ] 
} 
``` 
You may want to give the 2 modules better names to better identify which module they are, but any name will do as long as they are unique. Also I used `10.1.1.68` for the 2nd module but you'll need to change that to the actual IP address of the 2nd module.

BTW, I released a new version of the plugin today so you should upgrade to that one as it contains some changes that you'll need.

Hope that sort it out for you.

Regards

**Comment by jakubd2** [comment]
Thanks mantorok
The problem is I can’t get the module to allow me to enter the second module 
It just changes to the new module details
Do I just enter what you sent me into json node as administrator 
Regards 
Jakub

**Comment by mantorok1** [comment]
I'm not sure how you've set up your Homebridge but you need to be able to modify the raw json config.

I would recommend you copy the above config and paste it into Homebridge Config UI's Config Editor. It's the `Config` menu option on the top of the page.

If you're not using Homebridge Config UI then just use a text editor, edit the config.json file and paste the config & save.

In both cases you completely replace what's there with the above config.

**Comment by jakubd2** [comment]
Thanks matorok will try

**Comment by jakubd2** [comment]
Hey Mantorok1
You are a genius 
Everything works
Thankyou
Jakub

**Comment by mantorok1** [comment]
That's great news. Glad to hear its been resolved.

I'll close this issue.

Regards
