### ISSUE TITLE
Support for J-Series Rinnai Models?

### ISSUE THREAD

**Issue by mofolo** [mantorok1/homebridge-rinnai-touch-platform#7]
**Describe Your Problem:**
Hello, thanks so much for your contribution to homebridge! 
Question, I am looking to retrofit my home with smart air conditioners and I can see Rinnai have released the J series models which have WiFi built into them. 
Their manual details that:
```
Rinnai Split Type Wall Mounted Air Conditioner models HSNRJ25B, HSNRJ35B, HSNRJ50B, HSNRJ70B and
HSNRJ80B are fitted with built-in Wi-Fi connectivity. Using the AC Freedom App (available from Apple App Store
or Google Play) it is then possible to use a smart phone to operate these appliances remotely. Multiple compatible
appliances can be added as required
```
So I am assuming they don't use Zigbee to communicate between the Rinnai Touch WiFi module, but instead use IP to control the unit.
Does this plugin also support these units, or does it just support the WiFi module?

Googling around and found that the `AC Freedom App` doesn't have it's own Homebridge connector and looks to be made by this Asian company: http://www.aux-home.com/ 

**Logs:**
N/A

**Plugin Config:**
N/A

**Screenshots:**
N/A

**Environment:**

* **Plugin Version**:
N/A

**Comment by mantorok1** [comment]
I suspect it won't be compatible with the Rinnai Touch plugin. If the Air Con could be controlled by the Rinnai Touch iOS/Android  app then it might (and that's a BIG might) work with the plugin as it would probably be using the same connectivity and API as their Touch WiFi kit

**Comment by mofolo** [comment]
Thanks for the quick reply.
I did a bit more digging and it looks like these AUX Compatible devices use a generic Broadlink WiFi module which does have it's own Homebridge support plugin: https://github.com/makleso6/homebridge-broadlink-heater-cooler
Potentially that might work but really don't want to spend $1000's just to be the beta tester :D 

Thanks again!

**Comment by mantorok1** [comment]
Yeah, that's fair enough
