### ISSUE TITLE
Fan mode/speed option too limiting

### ISSUE THREAD

**Issue by bobbytables2048** [mantorok1/homebridge-rinnai-touch-platform#8]
**Is your feature request related to a problem? Please describe:**
I'm looking to use HomeBridge with your plugin to integrate my Brivis/Rinnai system with Home Assistant. This is by far the most stable integration I've seen for the Rinnai system yet.
My HVAC setup is as follows:
-   Ducted Gas with 4 zones
-   Evaporative Cooler
-  Rinnai/Brivis Wifi

I'm comfortable using MQTT.
Fan modes/speeds for the evap cooler is limited to low, medium and high. This is too limiting and I'm unable to select the slowest fan speed which we often use at night.

**Describe the solution you'd like:**
Fan modes/speeds for the evap cooler is limited to low, medium and high. The cooler fan can be set from 1 to 16 and having only 3 options available is limited. Low is not 1. Can this be changed to include at least 5 different speeds(1,4,8,12,16) or provide a config switch to allow all 16? 

**Describe alternatives you've considered:**
Another alternative would be to add back the native MQTT option. The evap fan speed could then be read and controlled with this topic, while all other controls and status are read from the HomeAssistant topics.

**Additional context:**
I've tried using the HomeKit Controller plugin for HomeAssistant. I run in a docker swarm using an overlay network so zeroconf will not work for discovery.
I've also tried using NodeRed with the HomeBridge plugin but this uses auto discovery also.
Lastly, I've tried sending the integer values through MQTT to this HomeBridge plugin but that does not work.

**Comment by mantorok1** [comment]
Hi @bobbytables2048,

If I modified the `hvac/fan_mode/set` MQTT topic to also accept an integer between 1 and 16 and set the fan speed on the Brivis/Rinnai accordingly would that provide the functionality you are after?

Currently the fan speed is set as follows:
* low = 5
* medium = 10
* high = 15

UPDATE:
Thinking a bit more about it, it might be better to add new topics, say `hvac/fan_speed/set` and `hvac/fan_speed/get`. Valid values for these would be integers between 1 and 16.

**Comment by mantorok1** [comment]
I've just released version 3.4.0 of the plugin. It contains new MQTT topics to allow finer control of the fan speed. Let me know if this solves the issue

**Comment by bobbytables2048** [comment]
@mantorok1 - I've just finished integrating it into home assistant and nodered. It is working well so far, thanks for the quick turn around time.

I have one more request for now (probably a few more once I integrate the heating zones fully). Is there a way via mqtt to switch the evap pump and to also put the evap into auto mode? The pump switch is important and the auto is less so as we don't use this mode that often. Let me know if you want a new feature request opened.

I recall from some of your early posts that you don't have evap, so I am happy to do testing for you.

**Comment by mantorok1** [comment]
Hi @bobbytables2048, glad to hear the new topics meet your needs.

For the pump switch I can add a couple more topics such as:
* `switch/pump/get`
* `switch/pump/set`

where the valid values would be `on` and `off`

For putting the evap into auto mode have you tried using the topic `switch/manual/set` with a value of `off`? I think it should work but as you mentioned I don't have an evap so could not really test it.

**Comment by bobbytables2048** [comment]
Hi @mantorok1 

The topics for pump will be OK. Let me know when I can upgrade and test for you.

I'll create a switch and test the auto mode today. I really appreciate the work you have done here and I hope these additional changes help other users of home assistant and openhab.

**Comment by mantorok1** [comment]
I've released version 3.4.1 which adds those pump topics. Give it a test and let me if works ok

**Comment by bobbytables2048** [comment]
HI @mantorok1 

I've been able to do some testing for the Evap Auto/Manual testing.

**First Test**
Send `switch/manual/set` the payload `on` and `off` 
This works to switch the evap between auto and manual.
The state is then published back on `switch/manual/u/get`, not on `switch/manual/get`

**Second Test**
Send the `on` and `off` payloads the the topic which is reported back.
`switch/manual/u/set` does not work for the auto evap mode.

**Third Test**
Set the mode to auto then reset homebridge to see what topics are being published, then switch to manual on the Rinnai/Brivis touch unit.

- 	`switch/manual/u/get` topic publishes from homebridge after a reset. 
- 	After setting manual on the touch unit, state publishing stops.

**Fourth Test**
Set the mode to manual then reset homebridge to see what topics are being published, then switch auto on the Rinnai/Brivis touch unit.

- 	`switch/manual/u/get` topic is not published after a reset.
- 	After setting auto on the touch unit, state publishing starts.

**Work around**
The manul vs auto mode can be identified through other topics:
For Auto mode

- 	`homebridge/brivis/hvac/action/get` = `{"U":"cooling"}`
- 	`hvac/mode/get` = `cool`
- 	`switch/evap/get` = `on`
- 	`switch/fan/get` = `off`

For Manual mode

- 	`homebridge/brivis/hvac/action/get` = `{"U":"fan"}`
- 	`hvac/mode/get` = `fan_only`
- 	`switch/evap/get` = `on`
- 	`switch/fan/get` = `on`

**Comment by mantorok1** [comment]
Do you have a Multi Set point config for your heating? That may explain why it's putting a `/u` in the topic.

**Comment by bobbytables2048** [comment]
With version 3.4.1, im unable to see the topic `switch/pump/get` and sending the payload on/off to `switch/pump/set` doesn't show in the homebridge logs and doesn't send any command back to the Rinnai/Brivis wifi unit.

For the manual/auto mode, yes I am configured for multi-setpoint. To determine the auto mode consistently, is there an easier method or do I need to map the states in my workaround?.

**Comment by mantorok1** [comment]
That's odd that the new `pump` topics are not working. You did restart Homebridge after upgrading the plugin right? Maybe try restarting again anyway and let me know.

For the manual/auto mode I think it's a bug. It should only include the zone in the topic for multi-setpoint which is not applicable to evap cooling. I'll get a fix ready for that

**Comment by bobbytables2048** [comment]
Another reset of homebridge has worked. I may have missed that step after the upgrade to 3.4.1

`switch/pump/get` works and shows the correct payload when the pump is on and off.
`switch/pump/set` = `on` errors with `Set ScheduleOverride to 'N' is invalid due to module's current Status`.
`switch/pump/set` = `off` errors with `Set ScheduleOverride to 'F' is invalid due to module's current Status`.

I appreciate the effort. You should add a 'buy me a beer' link in the readme.

**Comment by mantorok1** [comment]
I've just published version 3.4.2 which hopefully fixes the `switch/manual/get` and `switch/pump/set` issues.

I'm surprised no one else has found the bug with `switch/pump/set` as it would have affected the pump switch in HomeKit as well.

I did add a PayPal link to the readme if you'd like to make a donation.

**Comment by bobbytables2048** [comment]
Thanks @mantorok1,

Evap cooler pump and auto mode are now working well. I'll let you know if I find any other bugs while setting this up in HA, nodered and openhab.

Thanks for the weekend help, enjoy your beer donation!

**Comment by mantorok1** [comment]
Awesome! Thanks for the beer donation too.
